// Vercel serverless — sends a monthly analytics report email via Resend
// Required env vars: RESEND_API_KEY
// Optional env var: REPORT_FROM_EMAIL (defaults to onboarding@resend.dev for testing)

function barRows(items, total, color) {
  if (!items?.length) return "";
  return items
    .map((item) => {
      const pct = total > 0 ? Math.round((item.count / total) * 100) : 0;
      return `
      <tr>
        <td style="padding:6px 0;">
          <table width="100%" cellpadding="0" cellspacing="0">
            <tr>
              <td style="padding-bottom:4px;">
                <table width="100%" cellpadding="0" cellspacing="0"><tr>
                  <td style="font-size:14px;color:#292524;font-family:-apple-system,BlinkMacSystemFont,sans-serif">${escHtml(item.label)}</td>
                  <td align="right" style="font-size:12px;font-weight:700;color:#a8a29e;white-space:nowrap;font-family:-apple-system,sans-serif">${item.count}</td>
                </tr></table>
              </td>
            </tr>
            <tr>
              <td>
                <table width="100%" cellpadding="0" cellspacing="0" style="background:#e7e5e4;border-radius:6px;height:10px;">
                  <tr>
                    <td style="background:${color};border-radius:6px;height:10px;width:${pct}%;font-size:0">&nbsp;</td>
                    <td style="height:10px;font-size:0">&nbsp;</td>
                  </tr>
                </table>
              </td>
            </tr>
          </table>
        </td>
      </tr>`;
    })
    .join("");
}

function escHtml(str) {
  return String(str ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function sectionCard(title, body) {
  return `
  <tr><td style="padding-bottom:16px;">
    <table width="100%" cellpadding="0" cellspacing="0" style="background:#fff;border:1px solid #e7e5e4;border-radius:16px;">
      <tr><td style="padding:24px;">
        <p style="margin:0 0 16px;font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:0.18em;color:#a8a29e;font-family:-apple-system,sans-serif">${title}</p>
        ${body}
      </td></tr>
    </table>
  </td></tr>`;
}

function buildEmailHtml(hotelName, a, lang) {
  const isEs = lang === "es";
  const T = {
    title: isEs ? "Informe Mensual de Huéspedes" : "Monthly Guest Insights Report",
    subtitle: isEs ? "Últimos 30 días" : "Last 30 days",
    sessions: isEs ? "Sesiones" : "Sessions",
    itineraries: isEs ? "Itinerarios" : "Itineraries",
    chatOpens: isEs ? "Chats abiertos" : "Chat opens",
    favorites: isEs ? "Favoritos" : "Favorites",
    shares: isEs ? "Compartidos" : "Shares",
    guestPrefs: isEs ? "Preferencias del Huésped" : "Guest Preferences",
    questionnaires: isEs ? "cuestionarios" : "questionnaires",
    travelingAs: isEs ? "Viajando como" : "Traveling as",
    budget: isEs ? "Presupuesto" : "Budget",
    lengthOfStay: isEs ? "Duración de la estancia" : "Length of stay",
    travelStyle: isEs ? "Estilo de viaje" : "Travel style",
    top5: "(top 5)",
    foodPrefs: isEs ? "Preferencias alimentarias" : "Food preferences",
    transport: isEs ? "Transporte" : "Transport",
    topTopics: isEs ? "Temas más consultados en el chatbot" : "Top chatbot topics",
    languages: isEs ? "Idiomas" : "Languages",
    footer: isEs ? "Generado por Mi Concierge" : "Generated by Mi Concierge",
  };

  const month = new Date().toLocaleDateString(isEs ? "es-ES" : "en-GB", {
    month: "long",
    year: "numeric",
  });
  const q = a.questionnaire || {};

  const statCell = (val, label, color) => `
    <td style="padding:4px;" align="center">
      <table cellpadding="0" cellspacing="0" style="border:1px solid #e7e5e4;border-radius:12px;background:#fff;width:100%;">
        <tr><td style="padding:14px 6px;text-align:center;">
          <p style="margin:0;font-size:26px;font-weight:800;color:${color};font-family:-apple-system,sans-serif">${val ?? 0}</p>
          <p style="margin:5px 0 0;font-size:9px;color:#a8a29e;text-transform:uppercase;letter-spacing:0.1em;font-family:-apple-system,sans-serif">${label}</p>
        </td></tr>
      </table>
    </td>`;

  const prefCol = (sections) =>
    sections
      .filter(Boolean)
      .map(
        ([title, items, total, color]) =>
          `<p style="margin:0 0 8px;font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:0.12em;color:#a8a29e;font-family:-apple-system,sans-serif">${title}</p>
           <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:18px">${barRows(items, total, color)}</table>`
      )
      .join("");

  const topicsBody = (a.topTopics || [])
    .map(
      (t, i) => `
    <table width="100%" cellpadding="0" cellspacing="0">
      <tr style="border-bottom:1px solid #f5f5f4;">
        <td style="padding:8px 0;width:22px;font-size:11px;font-weight:700;color:#d4d4d4;font-family:-apple-system,sans-serif">${i + 1}</td>
        <td style="padding:8px 4px;font-size:14px;color:#292524;font-family:-apple-system,sans-serif">${escHtml(t.label)}</td>
        <td align="right" style="padding:8px 0;font-size:12px;font-weight:700;color:#a8a29e;white-space:nowrap;font-family:-apple-system,sans-serif">${t.count}×</td>
      </tr>
    </table>`
    )
    .join("");

  const langsBody = (a.langs || [])
    .map(
      (l) => `
    <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:10px">
      <tr>
        <td style="width:28px;font-size:11px;font-weight:700;text-transform:uppercase;color:#57534e;font-family:-apple-system,sans-serif">${escHtml(l.lang)}</td>
        <td style="padding:0 10px">
          <table width="100%" cellpadding="0" cellspacing="0" style="background:#e7e5e4;border-radius:4px;height:8px">
            <tr>
              <td style="background:#78716c;border-radius:4px;height:8px;width:${l.pct}%;font-size:0">&nbsp;</td>
              <td style="height:8px;font-size:0">&nbsp;</td>
            </tr>
          </table>
        </td>
        <td align="right" style="width:36px;font-size:12px;color:#a8a29e;font-family:-apple-system,sans-serif">${l.pct}%</td>
      </tr>
    </table>`
    )
    .join("");

  return `<!DOCTYPE html>
<html lang="${lang}">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${T.title}</title></head>
<body style="margin:0;padding:0;background:#fafaf9;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#fafaf9;">
<tr><td align="center" style="padding:24px 16px;">
<table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;">

  <!-- Header -->
  <tr><td style="padding-bottom:20px;">
    <table width="100%" cellpadding="0" cellspacing="0" style="background:#1c1917;border-radius:16px;">
      <tr><td style="padding:36px 32px;text-align:center;">
        <p style="margin:0 0 6px;font-size:10px;color:#78716c;text-transform:uppercase;letter-spacing:0.25em;font-family:-apple-system,sans-serif">${T.title}</p>
        <h1 style="margin:0 0 6px;font-size:28px;color:#fff;font-weight:700;font-family:-apple-system,sans-serif">${escHtml(hotelName)}</h1>
        <p style="margin:0;font-size:13px;color:#57534e;font-family:-apple-system,sans-serif">${month} · ${T.subtitle}</p>
      </td></tr>
    </table>
  </td></tr>

  <!-- Stats row -->
  <tr><td style="padding-bottom:20px;">
    <table width="100%" cellpadding="0" cellspacing="0"><tr>
      ${statCell(a.sessions, T.sessions, "#d97706")}
      ${statCell(a.generated, T.itineraries, "#292524")}
      ${statCell(a.chatOpens, T.chatOpens, "#292524")}
      ${statCell(a.favorites, T.favorites, "#d97706")}
      ${statCell(a.shares, T.shares, "#292524")}
    </tr></table>
  </td></tr>

  ${
    q.total > 0
      ? sectionCard(
          `${T.guestPrefs} — ${q.total} ${T.questionnaires}`,
          `<table width="100%" cellpadding="0" cellspacing="8"><tr>
            <td width="50%" style="vertical-align:top;padding-right:12px">
              ${prefCol([
                [T.travelingAs, q.group, q.total, "#d97706"],
                [T.budget, q.budget, q.total, "#78716c"],
                [T.lengthOfStay, q.days, q.total, "#78716c"],
              ])}
            </td>
            <td width="50%" style="vertical-align:top;padding-left:12px">
              ${prefCol([
                [T.travelStyle + " " + T.top5, q.style, q.styleTotal || 1, "#d97706"],
                [T.foodPrefs + " " + T.top5, q.food, q.foodTotal || 1, "#78716c"],
                [T.transport, q.transport, q.transportTotal || 1, "#78716c"],
              ])}
            </td>
          </tr></table>`
        )
      : ""
  }

  ${a.topTopics?.length ? sectionCard(T.topTopics, topicsBody) : ""}
  ${a.langs?.length ? sectionCard(T.languages, langsBody) : ""}

  <!-- Footer -->
  <tr><td style="padding:4px 0 32px;text-align:center;">
    <p style="margin:0;font-size:11px;color:#a8a29e;font-family:-apple-system,sans-serif">
      ${T.footer} · ${new Date().toLocaleDateString(isEs ? "es-ES" : "en-GB", { day: "numeric", month: "long", year: "numeric" })}
    </p>
  </td></tr>

</table>
</td></tr>
</table>
</body></html>`;
}

module.exports = async function handler(req, res) {
  if (req.method !== "POST") return res.status(405).end();

  const { hotelName, recipientEmail, analytics, lang } = req.body || {};
  if (!recipientEmail || !analytics) {
    return res.status(400).json({ error: "Missing recipientEmail or analytics." });
  }

  const RESEND_API_KEY = process.env.RESEND_API_KEY;
  if (!RESEND_API_KEY) {
    return res.status(503).json({
      error: "Email service not configured. Add RESEND_API_KEY to your Vercel environment variables.",
    });
  }

  const isEs = lang === "es";
  const month = new Date().toLocaleDateString(isEs ? "es-ES" : "en-GB", {
    month: "long",
    year: "numeric",
  });
  const subject = isEs
    ? `Informe mensual de huéspedes — ${hotelName} — ${month}`
    : `Monthly Guest Insights Report — ${hotelName} — ${month}`;

  const html = buildEmailHtml(hotelName || "Hotel", analytics, lang || "en");

  try {
    const emailRes = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${RESEND_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: process.env.REPORT_FROM_EMAIL || "Mi Concierge <onboarding@resend.dev>",
        to: [recipientEmail],
        subject,
        html,
      }),
    });

    if (!emailRes.ok) {
      const err = await emailRes.json().catch(() => ({}));
      return res.status(500).json({ error: err.message || "Email delivery failed." });
    }
    return res.status(200).json({ success: true });
  } catch (e) {
    console.error("send-report error:", e);
    return res.status(500).json({ error: "Internal error sending email." });
  }
};
